FROM node:20-alpine AS builder

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@9 --activate

COPY package*.json pnpm-lock.yaml* .npmrc ./
COPY prisma ./prisma/

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm run build
RUN pnpm exec prisma generate

EXPOSE 3000
CMD ["pnpm", "run", "start:dev"]