services:
  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     db:
  #       condition: service_healthy
  db:
    image: mongo:6.0
    container_name: mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: dev-db
    command: ["mongod","--bind_ip_all", "--replSet", "rs0"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "try { rs.status() } catch (err) { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'localhost:27017' }] }) }"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
