export enum MovieGenreEnum {
    ACTION = 'ACTION',
    ADVENTURE = 'ADVENTURE',
    COMEDY = 'COMEDY',
    DRAMA = 'DRAMA',
    HORROR = 'HORROR',
    ROMANCE = 'ROMANCE',
    SCIENCE_FICTION = 'SCIENCE_FICTION'
}